#pragma once

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 1024
#define VIEWPORT_MAP_WIDTH 512
#define VIEWPORT_MAP_HEIGHT 512
#define VIEWPORT_MAIN_WIDTH 512
#define VIEWPORT_MAIN_HEIGHT 512

#define MAP_V_WIDTH 16
#define MAP_V_HEIGHT 16
#define MAX_SND_CHANNELS 8

enum Structure {
    WALL_RED_STONE,
    WALL_GREY_CONCRETE_BRICK,
    WALL_RED_BRICK,
    WALL_ORANGE_DOOR,
    WALL_GREEN_TEXTURE,
    WALL_GREEN_DECORATIVE
};

enum Level {
    LEVEL_1,
    LEVEL_2,
    LEVEL_3
};